### ISSUE TITLE
Query-Related Swagger Resource?

### ISSUE THREAD

**Issue by githoov** [looker/looker-sdk-ruby#29]
The following Swagger resource (`looker-sdk-ruby/test/looker/swagger.json`) seems to capture most of the user-related methods. Is there something similar for all of the query-related methods?

**Comment by jbandhauer** [comment]
The doc you found is a snapshot that is only intended for the minimal sanity-check testing in those test. (Note that the 'real' tests of the underlying sdk semantics live in the extensive Looker tests that are not publicly available - this SDK is intended to be generic and work with almost any valid swagger compliant server - which might have completely different semantics compared to the Looker server.)

It is assumed that people who want a *real* swagger.json for any specific version of Looker will fetch that doc from a live server (and perhaps then save it locally for future use or whatever). This is trivially easy from a browser or curl or whatever for any server that exposes the swagger.json publicly from
https://yourcompany.looker.com:19999/api/3.0/swagger.json. For a server that requires an api login to see the api docs, one can capture the doc using the chrome inspector after logging in to the api docs page. The api docs page will fetch the doc fresh every time one hits the 'Load' button and the text will then show up in the chrome inspector and can be copied and pasted.

Importantly, the swagger doc is also available from any logged-in sdk as 'sdk.swagger' in ruby hash form. So, from the sdk shell you can save the doc to file as json by simply doing:
```
File.write("swagger.json", sdk.swagger.to_json)
```

**Comment by githoov** [comment]
Wow—this is killer!

**Comment by indranisenacn** [comment]
Even in the live Looker instance, unable to find Query API in swagger. Is this due to permission issue? Thanks!

**Comment by githoov** [comment]
@indranisenacn did you try https://yourcompany.looker.com:19999/api/3.0/swagger.json ? If that doesn't work, you may try making the docs, at least temporarily, not require api credentials to view:

![image](https://cloud.githubusercontent.com/assets/2467394/9817943/b3c36a98-585a-11e5-9ee0-57d84efe6054.png)

**Comment by indranisenacn** [comment]
Hello @githoov, it does work now. The issue was version of the Looker instance that we were using, we have now upgraded to 3.28 and I am able to see Query API. Cheers!

**Comment by githoov** [comment]
Nice!
