### ISSUE TITLE
Fix readme errors

### ISSUE THREAD

**Issue by jgn** [looker/looker-sdk-ruby#32]
1. `users = sdk.all_user()` - you mean `sdk.all_users()`
2. `get_credentials_email` doesn't work - `/opt/boxen/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/looker-sdk-ruby-10ba1ca56f57/lib/looker-sdk/client/dynamic.rb:62:in `method_missing': undefined method `get_credentials_email' for #<LookerSDK::Client:0x007f8212854210> (NoMethodError)
	from basic.rb:38:in `<main>'`

A weak readme reduces confidence in the code/api.

**Comment by jbandhauer** [comment]
Thanks. There was some renaming a while back and the readme didn't get updated. Will fix.
