### ISSUE TITLE
This SDK can't do /users/{user_id}/credentials_email ?

### ISSUE THREAD

**Issue by jgn** [looker/looker-sdk-ruby#33]
Can your dynamic wrapper do the v3 /users/{user_id}/credentials_email ? (answer seems to be: no.)

**Comment by jbandhauer** [comment]
Works for me...
```
jband@ ~/looker/src/looker-sdk/shell (master)$ ruby shell.rb 
Connecting to Looker at 'https://localhost:19999/api/3.0/'
Looker is alive!
[1] pry(main)> sdk.user_credentials_email(9)
=> {:email=>"jband@looker.com",
 :created_at=>2014-02-28 11:05:10 -0800,
 :logged_in_at=>2015-09-08 12:00:15 -0700,
 :type=>"email",
 :is_disabled=>false,
 :password_reset_url=>nil,
 :url=>"https://localhost:19999/api/3.0/users/9/credentials_email",
 :user_url=>"https://localhost:19999/api/3.0/users/9",
 :can=>{}}

```

Please explain your problem a bit more, perhaps I can help.

**Comment by jgn** [comment]
Ah - parameter on user_credentials_email. I thought it was a method off of a user.

**Comment by jgn** [comment]
```
Connecting to Looker at 'https://localhost:19999/api/3.0/'
Looker is alive!
[1] pry(main)> sdk.user_credentials_email(3)
LookerSDK::NotFound: GET https://localhost:19999/api/3.0/users/3/credentials_email: 404 - Not found // See: http://docs.looker.com/
from /opt/boxen/rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/bundler/gems/looker-sdk-ruby-abff0fb200a4/lib/looker-sdk/response/raise_error.rb:15:in `on_complete'
```

**Comment by jgn** [comment]
Bit more, just to show that there's a user with id = 3:

```
$ ruby shell.rb
Connecting to Looker at 'https://localhost:19999/api/3.0/'
Looker is alive!
[1] pry(main)> sdk.alive
=> 200
[2] pry(main)> sdk.user(3)
=> {:id=>3,
 :first_name=>"John",
 :last_name=>"Norman",
 :avatar_url=>
  "https://www.gravatar.com/avatar/b9f047098e4ffbbc812a9ca9caba82e6?s=156&d=mm",
 :url=>"https://localhost:19999/api/3.0/users/3",
 :can=>{}}

[3] pry(main)> sdk.user_credentials_email(3)
LookerSDK::NotFound: GET https://localhost:19999/api/3.0/users/3/credentials_email: 404 - Not found // See: http://docs.looker.com/
from /opt/boxen/rbenv/versions/1.9.3-p550/lib/ruby/gems/1.9.1/bundler/gems/looker-sdk-ruby-abff0fb200a4/lib/looker-sdk/response/raise_error.rb:15:in `on_complete'
[4] pry(main)>
```

**Comment by jgn** [comment]
Maybe that user is an API user.

**Comment by jgn** [comment]
The user is not an API user, but the user *is* a SAML user. Would that make this request return a 404?

**Comment by jbandhauer** [comment]
Yes. If the resource does not exist then you will get a NotFound. So, if the user exists, but has no credentials_email then the resource you are asking for does not exist. This makes sense if your user only has credentials_saml, for instance, Same thing if the user making the request does not have permissions to access the resource - which might be part of the issue here... We show *all* users a limited view of all other users: names, email, avatar_url. But, only admins and the self-same user can see *all* the info about a specific user.

**Comment by jgn** [comment]
Very good.

The user is question was an API user, but did not have the admin role. I
added `admin` and it works now.

I think these constraints would be worthy for docs.



On Tue, Sep 8, 2015 at 9:37 PM, John Bandhauer <notifications@github.com>
wrote:

> Yes. If the resource does not exist then you will get a NotFound. So, if
> the user exists, but has no credentials_email then the resource you are
> asking for does not exist. This makes sense if your user only has
> credentials_saml, for instance, Same thing if the user making the request
> does not have permissions to access the resource - which might be part of
> the issue here... We show *all* users a limited view of all other users:
> names, email, avatar_url. But, only admins and the self-same user can see
> *all* the info about a specific user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/looker/looker-sdk-ruby/issues/33#issuecomment-138759005>
> .
>



-- 
John G. Norman • Chief Software Architect at Iora Health
<http://www.iorahealth.com>
  Note: We’ve moved -- new address:
    101 Tremont Street, 6th floor, Boston, MA 02108
