### ISSUE TITLE
Provide some hints about required roles to exercise methods

### ISSUE THREAD

**Issue by jgn** [looker/looker-sdk-ruby#35]
For docs: to hit an endpoint like `/users/<id>/user_roles` you need to be in the right role.

**Comment by jbandhauer** [comment]
Thanks @jgn  I added some general text to the SDK readme. But, we'll also be making a serious effort soon to really flesh out the documentation about each API endpoint - including what permissions are needed. That work will happen in Looker's private repo and will be surfaces in the API docs accessible directly from Looker instances.

**Comment by jgn** [comment]
Great. I will provide more notes if I encounter mysteries.

On Wed, Sep 9, 2015 at 5:25 PM, John Bandhauer <notifications@github.com>
wrote:

> Thanks @jgn <https://github.com/jgn> I added some general text to the SDK
> readme. But, we'll also be making a serious effort soon to really flesh out
> the documentation about each API endpoint - including what permissions are
> needed. That work will happen in Looker's private repo and will be surfaces
> in the API docs accessible directly from Looker instances.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/looker/looker-sdk-ruby/issues/35#issuecomment-139062298>
> .
>



-- 
John G. Norman • Chief Software Architect at Iora Health
<http://www.iorahealth.com>
  Note: We’ve moved -- new address:
    101 Tremont Street, 6th floor, Boston, MA 02108
