### ISSUE TITLE
Cannot set format in create_query_and_run_async(body)

### ISSUE THREAD

**Issue by MuhanZou** [looker/looker-sdk-ruby#45]
Hi, is there a way to set query string to create endpoint like http://LOOKER:19999/api/3.0/queries/run_async?format=csv? thanks!

**Comment by dthorpe** [comment]
Hi,

The `run_async` endpoint currently only supports returning JSON results.  The synchronous query endpoints (like `run_query()`) support csv, html, and other result formats.

I'm actually in the middle of reworking the async query implementation to support result formats - all the formats supported by the synchronous query endpoints except the image formats.  I hope to have it rolled out soon!

Check out the notes I wrote up for the 3.52 release on recent API changes: https://discourse.looker.com/t/api-changes-3-52/3031

Keep an eye on that API section on discourse.looker.com for additional info articles and announcements.

Thanks!
-Danny

**Comment by dthorpe** [comment]
Also note that `create_query_and_run_async()` endpoint will be going away.  Replace with calls to `create_query()` followed by (in 3.52+) `create_query_task()`

**Comment by MuhanZou** [comment]
Thanks Danny, yeah adding query string to run_async won't make any change on result format. Look forward to seeing async functions supporting formats!

**Comment by dthorpe** [comment]
New async `query_task` method group added in Looker 4.0 release supports caller choosing the result format.  See https://looker.com/docs/reference/api-and-integration/api-reference/query#run_query_async
