### ISSUE TITLE
Remove .ruby-version ?

### ISSUE THREAD

**Issue by jgn** [looker/looker-sdk-ruby#49]
Perhaps the Ruby version could be given in the spec; and be looser.

**Comment by dthorpe** [comment]
I added `s.required_ruby_version = '>= 1.9.3'` to the gemspec. Does this supercede the .ruby-version file?  I'm not sure of how these bits interact.

**Comment by dthorpe** [comment]
Resolved by https://github.com/looker/looker-sdk-ruby/commit/4a967fc7b899428a724c3acfd70679e04cce5fbc
