### ISSUE TITLE
Release new version of the gem

### ISSUE THREAD

**Issue by fabio-looker** [looker/looker-sdk-ruby#66]
Per customer request:

> There is a conflict in the current Looker Gem dependencies with the Google Ruby Gem. The current master Looker Gem has that dependency updated but it has not been released. We've been asked to directly link to the master branch on Github but that is not good form. We'd rather use the released Gem.

Per our internal discussion, this change might require a major version.
cc: @dthorpe

**Comment by davetchen** [comment]
@fabio-looker a release that updates the dependencies would be awesome! :+1:

**Comment by uberllama** [comment]
There is also a dependency on a very old version of addressable. When can we look forward to a new release?

**Comment by dthorpe** [comment]
looker-sdk v0.0.6 published to rubygems.org.

@uberllama the bump of the sawyer dependency to 0.8 also ups the addressable version reference.  Does this bump meet your need?

**Comment by uberllama** [comment]
Awesome thank you!
