### ISSUE TITLE
Faraday dependency makes the SDK incompatible with gems

### ISSUE THREAD

**Issue by mikeghen** [looker/looker-sdk-ruby#71]
We are not able to use this SDK with our applications because our gems require higher versions of Faraday.

**Comment by jkaster** [comment]
I think this has been falling off the radar due to lack of tags. @jbandhauer and @dthorpe I'm happy to discuss with you.

**Comment by mikeghen** [comment]
@uberllama, I just forked this repo and patched the issue I was having, I put out a PR here #72, tests are failing on that but I really don't care to look into why, it's no longer an issue, planning on just continuing to use my forked repo
